### ISSUE TITLE
GUI not recognizing mouse

### ISSUE THREAD

**Issue by jmadin** [cnr-isti-vclab/TagLab#5]
Hello. I'm a coral ecologist at the Hawaii Institute of Marine Biology trying out the TagLab project. I have managed to install the everything on my Mac, and it runs. However: 

1. the GUI doesn't appear until I do something with the file menu (like "Load Map"); and 
2. once the GUI appears I can click between text inputs, but I can't click buttons (e.g., "Cancel"), so I'm kind of stuck... 

Notes: I have python 3.7.7 installed. In addition to your installation instructions, I had to install "albumentations" and a (seemingly known) Qt issue preventing the GUI to start meant that I had to take "opencv-python" back to version 4.1.2.30.

**Comment by cignoni** [comment]
Hi, 
unfortunately the main development platform is windows and we succeeded to run it over linux. 
So first suggestion would be to try on a windows machine. However we are aware of Mac users and we will make effort to make it more easily runnable. 

In the medium term we will surely improve the deployment mechanism. So hopefully this process will become significantly easier. As final suggestion checkout the project in a few weeks because major release updates are planned. 

Thanks for raising the issue!

**Comment by jmadin** [comment]
No problems. I thought it was probably a platform issue. Perhaps mention on the README page that the app has only tested on a PC to avoid people trying on a Mac :).  Best wishes. 

PS. I may play around with it on my Mac and will let you know if I figure the issue out.
